/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_tran4f_utils_DiskUtils */

#ifndef _Included_com_github_tran4f_utils_DiskUtils
#define _Included_com_github_tran4f_utils_DiskUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_tran4f_utils_DiskUtils
 * Method:    isUSBDriver
 * Signature: (C)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_tran4f_utils_DiskUtils_isUSBDriver
  (JNIEnv *, jclass, jchar);

#ifdef __cplusplus
}
#endif
#endif